# Generated by Django 3.1.7 on 2021-09-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xword_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='puzzle',
            table='puzzle',
        ),
    ]
